version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:20"
      timezone: "Asia/Aqtobe"
    open-pull-requests-limit: 5
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:40"
      timezone: "Asia/Aqtobe"
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - ci
