import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function source(path) { return readFile(new URL(`../${path}`, import.meta.url), "utf8"); }

test("v0.19 release roadmap contains every sequential stage", async () => { const text = await source("lib/release-roadmap.ts"); for (const version of ["v0.19.0", "v0.19.1", "v0.19.2", "v0.19.3", "v0.19.4", "v0.19.5", "v0.19.6", "v0.19.7"]) assert.match(text, new RegExp(version.replaceAll(".", "\\."))); });
test("mobile shell keeps the four workspace areas and adds a Trust control", async () => { const header = await source("components/site/StitchHeader.tsx"); const switcher = await source("components/playground/MobileWorkspaceSwitcher.tsx"); assert.match(header, /hidden[^\n]+lg:block/); assert.match(header, /<AppDock/); for (const id of ["chat", "flow", "artifacts", "runs"]) assert.match(switcher, new RegExp(`id: \"${id}\"`)); assert.match(switcher, /TrustControlSheet/); });
test("chat runtime exposes structured memory and bounded multi-round tools", async () => { const memory = await source("lib/ai/memory.ts"); const tools = await source("lib/ai/tools/registry.ts"); assert.match(memory, /goals:/); assert.match(memory, /decisions:/); assert.match(memory, /constraints:/); assert.match(memory, /openTasks:/); assert.match(tools, /MAX_AI_TOOL_CALLS = 6/); assert.match(tools, /MAX_AI_TOOL_ROUNDS = 3/); });
test("v0.19 PWA update behavior survives later cache-version bumps", async () => { const documents = await source("lib/documents/extract.ts"); const sync = await source("app/api/account/workspace-sync/route.ts"); const worker = await source("public/sw.js"); const pwa = await source("components/pwa/PwaRuntime.tsx"); assert.match(documents, /application\/pdf/); assert.match(sync, /isTrustedRequestOrigin/); assert.match(sync, /2 \* 1024 \* 1024/); assert.match(worker, /CACHE_VERSION = \"v0\.20\.9\"/); assert.match(worker, /SKIP_WAITING/); assert.match(pwa, /data-pwa-update-prompt/); });
