import type { Metadata } from "next";

import { StitchFooter } from "@/components/site/StitchFooter";
import { StitchHeader } from "@/components/site/StitchHeader";
import { ErmaMemoryControl } from "@/components/vault/ErmaMemoryControl";
import { PrivacyControlCenter } from "@/components/vault/PrivacyControlCenter";
import { PrivacyModeSelector } from "@/components/vault/PrivacyModeSelector";
import { WorkspaceSyncPanel } from "@/components/vault/WorkspaceSyncPanel";
import { WorkspaceVault } from "@/components/vault/WorkspaceVault";
import { getLocale } from "@/lib/locale";

export const metadata: Metadata = { title: "Workspace Vault · TK LAB", description: "Export, verify, restore, synchronize, and erase TK LAB workspace data." };
export default async function WorkspaceVaultPage() { const locale = await getLocale(); const ru = locale === "ru"; return <><StitchHeader /><main className="stitch-container min-h-screen pb-section-gap pt-8 sm:pt-12"><section className="mb-8 border-b border-outline-variant/30 pb-8 sm:mb-10 sm:pb-10"><p className="label-caps text-secondary">TK LAB · DATA CONTROL</p><h1 className="display-title mt-4 max-w-5xl">{ru ? "Данные под вашим контролем" : "Your data, under your control"}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-on-surface-variant sm:text-lg">{ru ? "Local-first остаётся стандартом. Режим хранения, переносимая локальная копия, память Erma, опциональный encrypted-at-rest Sync и server-held account data управляются отдельно." : "Local-first remains the default. Storage mode, portable local data, Erma memory, optional encrypted-at-rest Sync, and server-held account data are controlled separately."}</p></section><PrivacyModeSelector locale={locale} /><WorkspaceVault locale={locale} /><ErmaMemoryControl locale={locale} /><section className="mt-8 border border-outline-variant/40 bg-surface-container-low p-5 text-sm leading-6 text-on-surface-variant"><p className="font-medium text-primary">{ru ? "Перед включением Sync" : "Before using Sync"}</p><p className="mt-2">{ru ? "Sync создаёт server-held D1 snapshot. Он шифруется на сервере at rest, но не является end-to-end encryption: TK LAB Worker обрабатывает plaintext для upload/restore/export. Личная память Erma в этом обновлении остаётся отдельным локальным хранилищем и не синхронизируется автоматически." : "Sync creates a server-held D1 snapshot. It is encrypted at rest on the server, but it is not end-to-end encryption: the TK LAB Worker processes plaintext for upload/restore/export. Erma personal memory remains a separate local store in this release and is not automatically synchronized."}</p></section><WorkspaceSyncPanel locale={locale} /><PrivacyControlCenter locale={locale} /></main><StitchFooter /></>; }
