import type { Locale } from "@/lib/i18n";

export function homeCopy(locale: Locale) {
  const ru = locale === "ru";
  return {
    locale, ru,
    open: ru ? "Открыть Erma" : "Open Erma",
    intro: ru ? "AI-среда для работы с продолжением." : "An AI workspace for work that continues.",
    hero: ru ? ["ОТ ВОПРОСА", "К РАБОТЕ."] : ["FROM A", "QUESTION", "TO WORK."],
    description: ru ? "Модель под задачу. Источники рядом с ответом. Версии, к которым можно вернуться." : "A mode for the task. Sources beside the answer. Versions you can return to.",
    follow: ru ? "Проследить одну задачу" : "Follow one task",
    demo: ru ? "Пример работы · без AI-запроса" : "Product walkthrough · no live AI request",
    prompt: ru ? "Сравни локальный архив и Workspace Sync. Используй документацию и составь чек-лист." : "Compare local archive and Workspace Sync. Use the documentation and make a checklist.",
    promptLabel: ru ? "Один запрос" : "One request",
    intentParts: ru ? ["Сравнение", "Документация", "Чек-лист"] : ["Comparison", "Documentation", "Checklist"],
    modelRoles: ru ? ["Быстрые задачи", "Разбор и сравнение", "Глубокий анализ"] : ["Quick tasks", "Analysis & comparison", "Deeper analysis"],
    stages: ru ? [
      { title: "СНАЧАЛА — ЗАДАЧА.", text: "Вопрос, источник и формат результата. Всё начинается с одного запроса.", label: "Запрос" },
      { title: "МАРШРУТ ПОД ЗАДАЧУ.", text: "Auto выбирает режим по сложности запроса. Маршрутизация выполняется на сервере.", label: "Auto" },
      { title: "РАБОТА С ИСТОЧНИКОМ.", text: "Erma может обратиться к документации. Результат инструмента появляется рядом с ответом.", label: "Инструмент" },
      { title: "ОТВЕТ С КОНТЕКСТОМ.", text: "Диалог можно отнести к проекту. Итоговый материал — сохранить в Файлах.", label: "Контекст" },
      { title: "ЕЩЁ ОДНА ВЕРСИЯ.", text: "Уточните запрос, создайте ветку или сохраните версию документа. Предыдущая работа остаётся доступной.", label: "Версии" },
      { title: "ОДНА РАБОЧАЯ СРЕДА.", text: "Ход работы, контекст, задачи и файлы — рядом с диалогом. От первого вопроса до материала, к которому стоит вернуться.", label: "Erma" },
    ] : [
      { title: "FIRST, THE TASK.", text: "A question, a source, and a useful format. Everything starts with the same request.", label: "Input" },
      { title: "A ROUTE FOR THE TASK.", text: "Auto selects a mode from the complexity of your request. Routing stays on the server.", label: "Auto" },
      { title: "WORK FROM A SOURCE.", text: "Erma can consult its documentation. Tool activity appears alongside the answer.", label: "Tools" },
      { title: "AN ANSWER IN CONTEXT.", text: "Group the conversation into a project. Keep the resulting material in Files.", label: "Context" },
      { title: "KEEP THE NEXT VERSION.", text: "Refine a prompt, branch a conversation, or save a document version. Earlier work stays within reach.", label: "Versions" },
      { title: "ONE WORKSPACE.", text: "Activity, context, tasks, and files beside the conversation. From the first question to something worth returning to.", label: "Erma" },
    ],
    tabs: ru ? ["Ход работы", "Контекст", "Задача", "Файлы"] : ["Activity", "Context", "Task", "Files"],
    project: ru ? "Данные Erma" : "Erma data",
    conversations: ru ? "Диалоги" : "Conversations",
    branch: ru ? "Уточнение · ветка" : "Refinement · branch",
    original: ru ? "Исходный диалог" : "Original conversation",
    local: ru ? "На этом устройстве" : "On this device",
    toolTitle: ru ? "Поиск в документации" : "Documentation search",
    toolResult: ru ? "Приватность и границы системы" : "Privacy and system boundaries",
    source: ru ? "Источник" : "Source",
    resultTitle: ru ? "Где остаётся работа" : "Where the work lives",
    result: ru ? "Локальный архив хранит диалоги в браузере. Workspace Sync — отдельный снимок на сервере, который вы создаёте вручную." : "Local archive keeps conversations in your browser. Workspace Sync is a separate server snapshot you create manually.",
    checks: ru ? ["Архив по умолчанию — на устройстве.", "Sync включается отдельно и вручную.", "Для генерации запрос уходит AI-провайдеру."] : ["Archive stays on-device by default.", "Sync is optional and manual.", "Generation sends the prompt to an AI provider."],
    draft: ru ? "Черновик" : "First draft",
    revised: ru ? "Чек-лист" : "Checklist",
    refine: ru ? "Сократи до трёх пунктов." : "Make it three actionable points.",
    file: ru ? "данные-erma.md" : "erma-data.md",
    quiet: ru ? ["СПРОСИТЬ.", "ПРОВЕРИТЬ.", "ПРОДОЛЖИТЬ."] : ["ASK.", "CHECK.", "CONTINUE."],
    quietText: ru ? "Первый ответ — начало работы." : "The first answer is a starting point.",
    iterationTitle: ru ? "Уточняйте. Сохраняйте ход работы." : "Refine it. Keep the trail.",
    iterationText: ru ? "Переключите версии этого примера. В Erma можно создавать ветки диалога и сохранять версии файлов." : "Switch between this example’s versions. In Erma, you can branch a conversation and save file versions.",
    versionLabel: ru ? "Версия примера" : "Example version",
    storage: ru ? "Локальное хранение — по умолчанию. Запросы и отправленные вложения обрабатываются внешними AI-провайдерами. Sync — отдельная опция, не автоматическая резервная копия." : "Local storage is the default. Prompts and sent attachments are processed by external AI providers. Sync is optional, not an automatic backup.",
    dataControl: ru ? "Управление данными" : "Data controls",
    release: ru ? "Продукт в работе" : "A product in progress",
    releaseLink: ru ? "Что изменилось" : "Read the changes",
    end: ru ? "ВАШ СЛЕДУЮЩИЙ ВОПРОС." : "YOUR NEXT QUESTION.",
    endNote: ru ? "Войдите через Google, чтобы открыть рабочую среду." : "Sign in with Google to enter the workspace.",
    skip: ru ? "Перейти к содержимому" : "Skip to content",
    skipFilm: ru ? "Перейти к версиям" : "Skip to versions",
  };
}

export type HomeCopy = ReturnType<typeof homeCopy>;
