import type { Locale } from "@/lib/i18n";
import type { PublicReleaseNote } from "@/lib/releases/types";

const RU: PublicReleaseNote[] = [
  { date: "08 авг. 2026", version: "v0.21.0", title: "Cognitive Router", summary: "Erma определяет тип задачи, свежесть данных, необходимость инструментов и бюджет проверки до генерации ответа.", changes: ["Добавлены маршруты conversation/analysis/math/research/fresh information/TK LAB policy/releases/documents/code/planning/comparison.", "Tool budget ограничивается одновременно route policy и capability matrix."] },
  { date: "08 авг. 2026", version: "v0.21.1", title: "Web Intelligence", summary: "Erma получает контролируемый live web search и чтение найденных источников.", changes: ["Поиск работает через server-side Brave Search gateway.", "Модель может открыть только result ID из поиска текущего запроса; arbitrary URL, private hosts, unsafe ports, oversized/non-text responses и excessive redirects блокируются."] },
  { date: "08 авг. 2026", version: "v0.21.2", title: "Deep Research", summary: "Research mode выполняет bounded multi-source поиск вместо одного поверхностного запроса.", changes: ["Research получает до 8 tool calls и 3 rounds.", "Verifier требует открытые независимые источники и отличает полноценную проверку от одного search snippet."] },
  { date: "08 авг. 2026", version: "v0.21.3", title: "TK LAB Knowledge Brain", summary: "Terms, Privacy, AUP, AI Transparency, Security, Product Facts и data routes становятся канонической базой знаний Erma.", changes: ["TK LAB policy/privacy вопросы больше не полагаются на память модели.", "Ответ может указывать реальную версию документа и внутренний canonical link."] },
  { date: "08 авг. 2026", version: "v0.21.4", title: "Release Intelligence", summary: "Erma ориентируется в Patch Notes и версиях TK LAB через release registry.", changes: ["Можно искать изменения по версии и сравнивать релизы.", "Release claims связываются с каноническими release sources."] },
  { date: "08 авг. 2026", version: "v0.21.5", title: "Math Engine & LaTeX", summary: "Математика получает deterministic verification и нативный LaTeX rendering в чате.", changes: ["Добавлены arithmetic, quadratic equations, statistics, determinants и polynomial derivative/integral tools без eval.", "MarkdownMessage рендерит inline/display math через KaTeX с MathML."] },
  { date: "08 авг. 2026", version: "v0.21.6", title: "Verify Before Answer", summary: "Planner → tools → verifier определяет, какие выводы действительно подтверждены.", changes: ["Math, current web, TK LAB knowledge, documents и sandbox имеют отдельные verification codes.", "Неполная проверка должна быть обозначена вместо уверенного предположения."] },
  { date: "08 авг. 2026", version: "v0.21.7", title: "Evidence & Citations", summary: "Erma разделяет web, TK LAB, math, document, code и internal evidence.", changes: ["Web/TK LAB evidence содержит реальные href, документы — имя и chunk, math/code — тип verifier evidence.", "UI показывает новые intelligence tools в activity/tool cards."] },
  { date: "08 авг. 2026", version: "v0.21.8", title: "Document Intelligence", summary: "Прикреплённые документы получают request-scoped chunk search вместо слепого чтения всего текста.", changes: ["До 96 chunks на запрос, релевантный поиск до 8 фрагментов.", "Document content остаётся untrusted user data и не создаёт новую server-side document database."] },
  { date: "08 авг. 2026", version: "v0.21.9", title: "Layered Memory", summary: "Контекст делится на working, episodic и semantic memory внутри текущего запроса.", changes: ["Goals/decisions/open tasks/constraints/facts выбираются по релевантности к route.", "Новый server layer честно имеет persistence=request-context-only и не выдаётся за скрытую долговременную память."] },
  { date: "08 авг. 2026", version: "v0.21.10", title: "Autonomous Planning", summary: "Erma выполняет bounded tool loops и прекращает их, когда verifier уже удовлетворён.", changes: ["Web research, math, documents и canonical knowledge используют разные бюджеты.", "После каждого round выполняется interim verification и early stop."] },
  { date: "08 авг. 2026", version: "v0.21.11", title: "Critic Council", summary: "Сложные evidence-backed задачи получают дополнительный bounded review pass.", changes: ["Researcher/skeptic/editor lenses сводятся в краткий contradictions/missing evidence/synthesis brief.", "Council не раскрывает chain-of-thought и не является отдельным источником фактов."] },
  { date: "08 авг. 2026", version: "v0.21.12", title: "Smart Model Routing", summary: "Erma · Auto теперь реально выбирает Lite/Core/Pro по route и complexity.", changes: ["Исправлен путь, где Auto раньше мог фактически оставаться на Lite.", "Явно выбранная пользователем модель не подменяется автоматически."] },
  { date: "08 авг. 2026", version: "v0.21.13", title: "Dynamic Context", summary: "В prompt попадает только контекст, релевантный текущей задаче, с разделением control и untrusted evidence.", changes: ["Route-aware memory, document catalog и freshness context собираются динамически.", "Trusted route/verifier/answer directives отделены от web/document/tool output и conversation memory."] },
  { date: "08 авг. 2026", version: "v0.21.14", title: "Code Lab Gateway", summary: "Code verification допускается только через отдельный изолированный sandbox, никогда внутри application Worker.", changes: ["Sandbox feature-gated: HTTPS endpoint, network off, temporary filesystem, wall-time/memory/process limits.", "Без CODE_SANDBOX_URL/TOKEN инструмент fail-closed и Erma не заявляет, что код был запущен."] },
  { date: "08 авг. 2026", version: "v0.21.15", title: "Erma Intelligence Engine — Quality Gate", summary: "Web, knowledge, math, evidence, documents, memory, routing и answer intelligence объединены в один проверяемый контур.", changes: ["Answer format выбирается по intent и verification state.", "Patch Notes, release identity, tests и Browser Assurance синхронизированы с Intelligence Engine."] },
];

const EN: PublicReleaseNote[] = [
  { date: "08 Aug 2026", version: "v0.21.0", title: "Cognitive Router", summary: "Erma classifies task intent, freshness, tool need, and verification budget before answering.", changes: ["Added conversation/analysis/math/research/fresh information/TK LAB policy/releases/documents/code/planning/comparison routes.", "Tool budgets are bounded by both route policy and the capability matrix."] },
  { date: "08 Aug 2026", version: "v0.21.1", title: "Web Intelligence", summary: "Erma gains controlled live web search and source reading.", changes: ["Search uses a server-side Brave Search gateway.", "The model can open only same-request search result IDs; arbitrary URLs, private hosts, unsafe ports, oversized/non-text responses, and excessive redirects are blocked."] },
  { date: "08 Aug 2026", version: "v0.21.2", title: "Deep Research", summary: "Research mode performs bounded multi-source investigation instead of a single shallow query.", changes: ["Research receives up to 8 tool calls and 3 rounds.", "The verifier requires opened independent sources and distinguishes verified research from search snippets alone."] },
  { date: "08 Aug 2026", version: "v0.21.3", title: "TK LAB Knowledge Brain", summary: "Terms, Privacy, AUP, AI Transparency, Security, Product Facts, and data routes become Erma's canonical TK LAB knowledge.", changes: ["TK LAB policy/privacy answers no longer rely on model memory.", "Answers can include the actual document version and canonical internal link."] },
  { date: "08 Aug 2026", version: "v0.21.4", title: "Release Intelligence", summary: "Erma navigates TK LAB Patch Notes and versions through the release registry.", changes: ["Release changes can be searched and compared by version.", "Release claims are tied to canonical release sources."] },
  { date: "08 Aug 2026", version: "v0.21.5", title: "Math Engine & LaTeX", summary: "Mathematics gains deterministic verification and native LaTeX rendering in chat.", changes: ["Added arithmetic, quadratic, statistics, determinant, and polynomial derivative/integral tools without eval.", "MarkdownMessage renders inline/display math through KaTeX with MathML."] },
  { date: "08 Aug 2026", version: "v0.21.6", title: "Verify Before Answer", summary: "Planner → tools → verifier records what was actually checked before synthesis.", changes: ["Math, current web, TK LAB knowledge, documents, and sandbox runs have scoped verification codes.", "Incomplete verification must be qualified rather than guessed through."] },
  { date: "08 Aug 2026", version: "v0.21.7", title: "Evidence & Citations", summary: "Erma separates web, TK LAB, math, document, code, and internal evidence.", changes: ["Web/TK LAB evidence carries real hrefs, documents carry name/chunk, and math/code carry verifier evidence.", "The activity UI exposes the new intelligence tools."] },
  { date: "08 Aug 2026", version: "v0.21.8", title: "Document Intelligence", summary: "Attached documents gain request-scoped chunk retrieval instead of blindly pushing all text into reasoning.", changes: ["Up to 96 chunks per request and up to 8 relevant retrieved fragments.", "Document content stays untrusted user data and no new server-side document database is introduced."] },
  { date: "08 Aug 2026", version: "v0.21.9", title: "Layered Memory", summary: "Context is organized into working, episodic, and semantic layers within the active request.", changes: ["Goals, decisions, open tasks, constraints, and facts are selected by route relevance.", "The new server layer explicitly reports persistence=request-context-only rather than claiming hidden long-term memory."] },
  { date: "08 Aug 2026", version: "v0.21.10", title: "Autonomous Planning", summary: "Erma runs bounded tool loops and stops once route verification is satisfied.", changes: ["Web research, math, documents, and canonical knowledge use different bounded budgets.", "Every round performs interim verification and supports early stop."] },
  { date: "08 Aug 2026", version: "v0.21.11", title: "Critic Council", summary: "Complex evidence-backed work can receive one additional bounded review pass.", changes: ["Researcher/skeptic/editor lenses produce a concise contradictions/missing evidence/synthesis brief.", "The council exposes no chain-of-thought and is not treated as a factual source."] },
  { date: "08 Aug 2026", version: "v0.21.12", title: "Smart Model Routing", summary: "Erma · Auto now genuinely selects Lite/Core/Pro using route and task complexity.", changes: ["Fixed the request path where Auto could effectively remain on Lite.", "An explicitly selected user model is never silently replaced by Auto."] },
  { date: "08 Aug 2026", version: "v0.21.13", title: "Dynamic Context", summary: "Prompts receive only task-relevant context with a strict control/evidence trust boundary.", changes: ["Route-aware memory, document catalog, and freshness context are assembled dynamically.", "Trusted route/verifier/answer directives are separated from web/document/tool output and conversation memory."] },
  { date: "08 Aug 2026", version: "v0.21.14", title: "Code Lab Gateway", summary: "Code verification is permitted only through a separate isolated sandbox, never inside the application Worker.", changes: ["Sandbox integration is feature-gated: HTTPS endpoint, network off, temporary filesystem, and wall-time/memory/process limits.", "Without CODE_SANDBOX_URL/TOKEN the tool fails closed and Erma cannot claim execution."] },
  { date: "08 Aug 2026", version: "v0.21.15", title: "Erma Intelligence Engine — Quality Gate", summary: "Web, knowledge, math, evidence, documents, memory, routing, and answer intelligence are unified into one testable system.", changes: ["Answer shape is selected by intent and verification state.", "Patch Notes, release identity, tests, and Browser Assurance are synchronized with Intelligence Engine."] },
];

export function getIntelligenceEngineReleases(locale: Locale) {
  return (locale === "ru" ? RU : EN).map((entry) => ({ ...entry, changes: [...entry.changes] }));
}
