import type { Locale } from "@/lib/i18n";
import type { PublicReleaseNote } from "@/lib/releases/types";

const RU: PublicReleaseNote[] = [
  { date: "08 авг. 2026", version: "v0.20.10", title: "Mobile Fixed Layers", summary: "Мобильные соглашения, навигация и рабочие панели больше не зависят от длины страницы или позиции прокрутки.", changes: ["TermsGate вынесен в body-level viewport portal: соглашение сразу открывается в текущем экране, а прокручивается только его текст.", "Кнопки принятия/отказа закреплены внутри видимого legal viewport и учитывают safe-area.", "Public AppDock и mobile workspace dock стали независимыми fixed viewport layers и остаются видимыми при длинной странице или чате.", "Chat/Trust overlays и mobile drawer используют единый reference-counted scroll lock, чтобы фон не уезжал под модалкой.", "Browser Assurance теперь отдельно проверяет длинную страницу, pinned navigation и legal actions на Chromium/WebKit mobile."] },
  { date: "08 авг. 2026", version: "v0.20.0", title: "Product Truth Foundation", summary: "Единый реестр фактов о хранении, provider processing и позиционировании local-first.", changes: ["Добавлен Product Facts Registry как проверяемый источник privacy/product truth.", "Local, Synced и Ephemeral маршруты явно отделены от on-device inference.", "Зафиксированы инварианты полного цикла Trust Architecture."] },
  { date: "08 авг. 2026", version: "v0.20.1", title: "Legal Center 2.0", summary: "Версионируемый legal bundle и доказуемый append-only consent ledger.", changes: ["Добавлены Privacy, Acceptable Use, AI Transparency, Subprocessors и Security surfaces.", "Согласие хранит version, digest, language и acceptedAt в D1 ledger.", "Operator/contact/jurisdiction берутся из явной production configuration, а не выдумываются приложением."] },
  { date: "08 авг. 2026", version: "v0.20.2", title: "Privacy Control Center", summary: "Пользователь может отдельно экспортировать и удалять local и server-held данные TK LAB.", changes: ["Добавлены local/server export, clear local и DELETE Workspace Sync.", "Account data deletion требует явной confirmation phrase и trusted origin.", "Опубликован retention schedule с границами внешних провайдеров."] },
  { date: "08 авг. 2026", version: "v0.20.3", title: "Privacy Modes", summary: "Local / Synced / Ephemeral становятся реальными режимами хранения, а не маркетинговыми ярлыками.", changes: ["Ephemeral не записывает новые chat sessions в локальный archive.", "Ephemeral блокирует создание server Sync snapshot.", "Data Route Inspector показывает, что AI inference всё равно использует TK LAB Worker и внешний provider."] },
  { date: "08 авг. 2026", version: "v0.20.4", title: "Security & Crypto v2", summary: "Workspace Sync получает versioned cryptography, а browser CSP становится уже.", changes: ["HKDF-SHA-256 разделяет AES-GCM encryption и HMAC integrity keys.", "AAD связывает account, revision и key version; legacy v1 snapshot переупаковывается после успешного чтения.", "Browser connect-src ограничен self, inline script attributes запрещены, security.txt опубликован."] },
  { date: "08 авг. 2026", version: "v0.20.5", title: "Unified Policy Engine", summary: "Runtime safety и публичный Acceptable Use используют одну versioned taxonomy.", changes: ["Добавлены allowed / restricted / high-impact / harmful / prompt-injection / secret-extraction categories.", "Legacy refusal reasons сохранены для совместимости, решения получают stable policy code.", "Attachments и read-only tool results явно маркируются как untrusted external data."] },
  { date: "08 авг. 2026", version: "v0.20.6", title: "AI Transparency & Provenance", summary: "Каждый новый AI response получает безопасные provenance metadata, а Erma — честные model cards.", changes: ["Provenance фиксирует TK LAB version, policy version, product model, provider class и time.", "Hidden prompts, credentials и chain-of-thought не включаются в provenance.", "Transparency page показывает реальные data routes и ограничения Erma Lite/Core/Pro."] },
  { date: "08 авг. 2026", version: "v0.20.7", title: "Trust UX & Mobile Control Center", summary: "Privacy и provider disclosure становятся частью рабочего интерфейса на mobile и desktop.", changes: ["Mobile Workspace получает Trust sheet и управление privacy mode.", "Первый mobile visit показывает just-in-time disclosure о передаче AI requests/attachments.", "Vault отдельно предупреждает, что Sync — server-side encrypted-at-rest, не end-to-end encryption."] },
  { date: "08 авг. 2026", version: "v0.20.8", title: "Operations & Governance", summary: "Incident history, audit events и recovery drills получают проверяемые правила без имитации uptime.", changes: ["Публичный incident registry append-only и не превращает отсутствие записей в 100% uptime claim.", "Content-free audit events ограничены 90 днями.", "Добавлены crypto rotation, D1 restore, provider outage и legal re-consent drills."] },
  { date: "08 авг. 2026", version: "v0.20.9", title: "Trust Architecture — Launch Quality Gate", summary: "Весь trust-контур сводится в единый релизный и CI-контракт.", changes: ["Добавлены legal/privacy/policy/trust consistency gates.", "Release identity, PWA cache, документация и Updates синхронизированы на v0.20.9.", "Preview остаётся честно preview: коммерческий launch gate требует реальные operator/contact/jurisdiction values."] },
];

const EN: PublicReleaseNote[] = [
  { date: "08 Aug 2026", version: "v0.20.10", title: "Mobile Fixed Layers", summary: "Mobile consent, navigation, and workspace controls no longer depend on document length or scroll position.", changes: ["TermsGate now renders through a body-level viewport portal: the agreement opens in the current screen while only its document content scrolls.", "Accept/decline controls stay inside the visible legal viewport and respect safe-area insets.", "Public AppDock and mobile workspace dock are independent fixed viewport layers that remain visible across long pages and chats.", "Chat/Trust overlays and the mobile drawer share a reference-counted document scroll lock so the background cannot drift underneath them.", "Browser Assurance now covers tall-page consent, pinned navigation, and legal actions on mobile Chromium/WebKit."] },
  { date: "08 Aug 2026", version: "v0.20.0", title: "Product Truth Foundation", summary: "One registry for storage, provider processing, and local-first positioning facts.", changes: ["Added a Product Facts Registry as a verifiable privacy/product truth source.", "Local, Synced, and Ephemeral routes are explicitly separated from on-device inference.", "Recorded invariants for the full Trust Architecture cycle."] },
  { date: "08 Aug 2026", version: "v0.20.1", title: "Legal Center 2.0", summary: "A versioned legal bundle backed by an append-only consent ledger.", changes: ["Added Privacy, Acceptable Use, AI Transparency, Subprocessors, and Security surfaces.", "Consent evidence records version, digest, language, and acceptedAt in D1.", "Operator/contact/jurisdiction come from explicit production configuration rather than invented app copy."] },
  { date: "08 Aug 2026", version: "v0.20.2", title: "Privacy Control Center", summary: "Users can independently export and erase TK LAB local and server-held data.", changes: ["Added local/server export, clear-local, and DELETE Workspace Sync.", "Account-data deletion requires an explicit confirmation phrase and trusted origin.", "Published a retention schedule with external-provider boundaries."] },
  { date: "08 Aug 2026", version: "v0.20.3", title: "Privacy Modes", summary: "Local / Synced / Ephemeral become real storage behavior rather than labels.", changes: ["Ephemeral does not archive new chat sessions locally.", "Ephemeral blocks creation of a server Sync snapshot.", "Data Route Inspector makes clear that AI inference still uses the TK LAB Worker and an external provider."] },
  { date: "08 Aug 2026", version: "v0.20.4", title: "Security & Crypto v2", summary: "Workspace Sync gets versioned cryptography while browser CSP is narrowed.", changes: ["HKDF-SHA-256 separates AES-GCM encryption and HMAC integrity keys.", "AAD binds account, revision, and key version; legacy v1 snapshots are re-sealed after successful reads.", "Browser connect-src is self-only, inline script attributes are denied, and security.txt is published."] },
  { date: "08 Aug 2026", version: "v0.20.5", title: "Unified Policy Engine", summary: "Runtime safety and the public Acceptable Use Policy share one versioned taxonomy.", changes: ["Added allowed / restricted / high-impact / harmful / prompt-injection / secret-extraction categories.", "Legacy refusal reasons remain compatible while decisions gain stable policy codes.", "Attachments and read-only tool results are explicitly marked as untrusted external data."] },
  { date: "08 Aug 2026", version: "v0.20.6", title: "AI Transparency & Provenance", summary: "New AI responses carry safe provenance metadata and Erma receives honest model cards.", changes: ["Provenance records TK LAB version, policy version, product model, provider class, and time.", "Hidden prompts, credentials, and chain-of-thought are excluded from provenance.", "The Transparency page shows real data routes and Erma Lite/Core/Pro limitations."] },
  { date: "08 Aug 2026", version: "v0.20.7", title: "Trust UX & Mobile Control Center", summary: "Privacy and provider disclosure become first-class workspace UI on mobile and desktop.", changes: ["Mobile Workspace gains a Trust sheet and privacy-mode controls.", "The first mobile visit shows a just-in-time disclosure for AI requests and submitted attachments.", "Vault explicitly states that Sync is server-side encrypted at rest, not end-to-end encryption."] },
  { date: "08 Aug 2026", version: "v0.20.8", title: "Operations & Governance", summary: "Incident history, audit events, and recovery drills gain evidence-backed rules without fabricated uptime.", changes: ["The public incident registry is append-only and never turns an empty list into a 100% uptime claim.", "Content-free audit events are bounded to 90 days.", "Added crypto rotation, D1 restore, provider outage, and legal re-consent drills."] },
  { date: "08 Aug 2026", version: "v0.20.9", title: "Trust Architecture — Launch Quality Gate", summary: "The complete trust layer is unified into one release and CI contract.", changes: ["Added legal/privacy/policy/trust consistency gates.", "Release identity, PWA cache, documentation, and Updates are synchronized to v0.20.9.", "Preview remains explicitly preview; commercial launch requires real operator/contact/jurisdiction values."] },
];

export function getTrustArchitectureReleases(locale: Locale) {
  return (locale === "ru" ? RU : EN).map((entry) => ({ ...entry, changes: [...entry.changes] }));
}
