import Link from "next/link";
import { ArrowLeft, CheckCircle2, CircleAlert, ExternalLink } from "lucide-react";

const incidents = [
  {
    date: "2026-01-18",
    status: "resolved",
    title: "Imagination failed open in hall B-2",
    body: "A warm event in the coolant loop caused three dashboards to display confidence they did not possess.",
    duration: "17 min",
  },
  {
    date: "2026-01-12",
    status: "resolved",
    title: "Latency exceeded the speed of thought",
    body: "The public demo briefly returned an answer before the prompt was submitted. We added a polite 412ms delay.",
    duration: "4 min",
  },
  {
    date: "2026-01-03",
    status: "monitoring",
    title: "Confidence theater under observation",
    body: "The number is stable, the number is green, and the number has no legal standing.",
    duration: "ongoing",
  },
];

export function StatusPage() {
  return (
    <main className="status-page-shell">
      <header className="status-page-header">
        <Link className="status-back" href="/">
          <ArrowLeft size={14} aria-hidden="true" /> back to facility
        </Link>
        <div className="status-brand">II / public status</div>
        <span className="status-date">last updated just now</span>
      </header>
      <section className="status-hero">
        <div>
          <span className="eyebrow text-[#e7ff49]">SYSTEM STATUS / 2026</span>
          <h1>Everything is<br /><em>mostly fine.</em></h1>
          <p>
            A satirical status page for a fictional AI facility. The incidents
            are made up. The latency badge on the demo is not.
          </p>
        </div>
        <div className="status-orb" aria-label="All fictional systems operational">
          <span className="status-orb-ring" />
          <strong>99.97%</strong>
          <small>uptime / alleged</small>
          <span className="status-orb-state"><CheckCircle2 size={14} /> all fictional systems operational</span>
        </div>
      </section>
      <section className="status-systems" aria-label="System status">
        {[
          ["Public facility", "operational"],
          ["Proof console", "operational"],
          ["Confidence layer", "monitoring"],
          ["Legal disclosure", "operational"],
        ].map(([label, state]) => (
          <div className="system-row" key={label}>
            <span className={state === "monitoring" ? "system-icon monitoring" : "system-icon"}>
              {state === "monitoring" ? <CircleAlert size={14} /> : <CheckCircle2 size={14} />}
            </span>
            <span>{label}</span>
            <strong>{state}</strong>
          </div>
        ))}
      </section>
      <section className="incident-list">
        <div className="incident-list-heading">
          <span className="eyebrow">incident history</span>
          <span>root cause analysis / occasionally honest</span>
        </div>
        {incidents.map((incident) => (
          <article className="incident-card" key={incident.title}>
            <div className="incident-marker" />
            <div className="incident-date">{incident.date}</div>
            <div className="incident-copy">
              <div className="incident-status">{incident.status} / {incident.duration}</div>
              <h2>{incident.title}</h2>
              <p>{incident.body}</p>
            </div>
            <ExternalLink className="incident-link" size={16} aria-hidden="true" />
          </article>
        ))}
      </section>
      <footer className="status-page-footer">
        <span>incident feed generated by a deterministic seed</span>
        <Link href="/truth">read the disclosure <ExternalLink size={13} /></Link>
      </footer>
    </main>
  );
}
